[INFO | transformer | L28] 2024-12-07T22:16:44+0000: Wrote ['BF2_BFBD Furnace Body 12975mm Temp A', 'BF2_BFBD Furnace Body 12975mm Temp B', 'BF2_BFBD Furnace Body 12975mm Temp C', 'BF2_BFBD Furnace Body 12975mm Temp D', 'BF2_BFBD Furnace Body 15162mm Temp A', 'BF2_BFBD Furnace Body 15162mm Temp A', 'BF2_BFBD Furnace Body 15162mm Temp A', 'BF2_BFBD Furnace Body 15162mm Temp A', 'BF2_BFBD Furnace Body 15162mm Temp A'] of temperature_variables for 2024-12-07 22:14:53. | transformer.py
[INFO | transformer | L28] 2024-12-07T22:17:16+0000: Wrote ['BF2 Coal flow switch No 1', 'BF2 Coal flow switch No 10', 'BF2 Coal flow switch No 11', 'BF2 Coal flow switch No 12', 'BF2 Coal flow switch No 13'] of switch_variables for 2024-12-07 22:14:53. | transformer.py
[INFO | pipeline | L27] 2024-12-07T22:17:25+0000: Data preprocessing complete. | pipeline.py
[INFO | task_engine | L272] 2024-12-07T22:17:26+0000: Finished in state Completed() | task_engine.py
[INFO | _client | L1742] 2024-12-07T22:17:27+0000: HTTP Request: POST http://127.0.0.1:8892/api/logs/ "HTTP/1.1 201 Created" | _client.py
[INFO | pipeline | L35] 2024-12-07T22:17:27+0000: Starting data write task... | pipeline.py
[INFO | writer | L24] 2024-12-07T22:17:28+0000: Called the influxdb client <influxdb_client_3.InfluxDBClient3 object at 0x0000025D483D03E0>. | writer.py
[ERROR | task_engine | L554] 2024-12-07T22:17:28+0000: Task run failed with exception: AttributeError("'InfluxDBClient3' object has no attribute 'write_api'") - Retries are exhausted | task_engine.py
Traceback (most recent call last):
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\task_engine.py", line 781, in run_context
    yield self
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\task_engine.py", line 1337, in run_task_sync
    engine.call_task_fn(txn)
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\task_engine.py", line 804, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\src\workflows\pipeline.py", line 36, in write_data_task
    write_to_influxdb(config, validated_data)
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\src\data\writer.py", line 25, in write_to_influxdb
    write_api = client.write_api()
                ^^^^^^^^^^^^^^^^
AttributeError: 'InfluxDBClient3' object has no attribute 'write_api'. Did you mean: '_write_api'?
[ERROR | task_engine | L272] 2024-12-07T22:17:28+0000: Finished in state Failed("Task run encountered an exception AttributeError: 'InfluxDBClient3' object has no attribute 'write_api'") | task_engine.py
[ERROR | flow_engine | L725] 2024-12-07T22:17:28+0000: Encountered exception during execution: AttributeError("'InfluxDBClient3' object has no attribute 'write_api'") | flow_engine.py
Traceback (most recent call last):
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\flow_engine.py", line 721, in run_context
    yield self
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\flow_engine.py", line 1331, in run_flow_sync
    engine.call_flow_fn()
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\flow_engine.py", line 744, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\src\workflows\pipeline.py", line 50, in data_pipeline
    write_data_task(validated_data, config)
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\tasks.py", line 1002, in __call__
    return run_task(
           ^^^^^^^^^
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\task_engine.py", line 1526, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\task_engine.py", line 1339, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
                                                       ^^^^^^^^^^^^^^^
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\task_engine.py", line 482, in result
    raise self._raised
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\task_engine.py", line 781, in run_context
    yield self
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\task_engine.py", line 1337, in run_task_sync
    engine.call_task_fn(txn)
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\task_engine.py", line 804, in call_task_fn
    result = call_with_parameters(self.task.fn, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\.venv\Lib\site-packages\prefect\utilities\callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\src\workflows\pipeline.py", line 36, in write_data_task
    write_to_influxdb(config, validated_data)
  File "e:\Personal\MarketResearch\EvonithSteel\Blast Furnace Project\PythonBlastFurnace\evonith_datafeed_job\src\data\writer.py", line 25, in write_to_influxdb
    write_api = client.write_api()
                ^^^^^^^^^^^^^^^^
AttributeError: 'InfluxDBClient3' object has no attribute 'write_api'. Did you mean: '_write_api'?
[INFO | _client | L1027] 2024-12-07T22:17:28+0000: HTTP Request: POST http://127.0.0.1:8892/api/flow_runs/a1a075e3-249e-48d6-87f4-b429cef514d7/set_state "HTTP/1.1 201 Created" | _client.py
[ERROR | flow_engine | L685] 2024-12-07T22:17:28+0000: Finished in state Failed("Flow run encountered an exception: AttributeError: 'InfluxDBClient3' object has no attribute 'write_api'") | flow_engine.py
[INFO | _client | L1742] 2024-12-07T22:17:29+0000: HTTP Request: POST http://127.0.0.1:8892/api/logs/ "HTTP/1.1 201 Created" | _client.py
[INFO | server | L862] 2024-12-07T22:17:32+0000: Stopping temporary server on http://127.0.0.1:8892 | server.py
[INFO | app | L11] 2024-12-07T23:22:47+0000: Starting the data pipeline | app.py
[INFO | server | L784] 2024-12-07T23:22:49+0000: Starting temporary server on http://127.0.0.1:8437
See https://docs.prefect.io/3.0/manage/self-host#self-host-a-prefect-server for more information on running a dedicated Prefect server. | server.py
[INFO | _client | L1027] 2024-12-07T23:22:56+0000: HTTP Request: GET http://127.0.0.1:8437/api/health "HTTP/1.1 200 OK" | _client.py
[INFO | _client | L1027] 2024-12-07T23:22:56+0000: HTTP Request: GET http://127.0.0.1:8437/api/admin/version "HTTP/1.1 200 OK" | _client.py
[INFO | _client | L1027] 2024-12-07T23:22:56+0000: HTTP Request: GET http://127.0.0.1:8437/api/csrf-token?client=fd93486c-dba5-445a-994c-203b6b98ea39 "HTTP/1.1 422 Unprocessable Entity" | _client.py
[INFO | _client | L1027] 2024-12-07T23:22:57+0000: HTTP Request: POST http://127.0.0.1:8437/api/flows/ "HTTP/1.1 200 OK" | _client.py
[INFO | _client | L1027] 2024-12-07T23:22:57+0000: HTTP Request: POST http://127.0.0.1:8437/api/flow_runs/ "HTTP/1.1 201 Created" | _client.py
[INFO | flow_engine | L496] 2024-12-07T23:22:57+0000: Created flow run 'cuddly-shark' for flow 'data-pipeline' | flow_engine.py
[INFO | _client | L1027] 2024-12-07T23:22:57+0000: HTTP Request: POST http://127.0.0.1:8437/api/flow_runs/405193cc-e204-4814-93d2-dc74c5f6f5b3/set_state "HTTP/1.1 201 Created" | _client.py
[INFO | _client | L1027] 2024-12-07T23:22:57+0000: HTTP Request: GET http://127.0.0.1:8437/api/flow_runs/405193cc-e204-4814-93d2-dc74c5f6f5b3 "HTTP/1.1 200 OK" | _client.py
[INFO | pipeline | L44] 2024-12-07T23:22:57+0000: Starting data pipeline... | pipeline.py
[INFO | pipeline | L15] 2024-12-07T23:22:57+0000: Starting download task... | pipeline.py
[INFO | helper_functions_downloader | L36] 2024-12-07T23:22:57+0000: No CSV files found to delete. | helper_functions_downloader.py
